import Head from 'next/head'
import { NextPageContext } from 'next'
import { getSession, signOut } from 'next-auth/react'
import useCurrentUser from '@/components/useCurrentUser'

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return {
    props: {}
  }
}

export default function Home() {
  const query = useCurrentUser()
  console.log(query.data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-white'>Hello World</h1>
        <button className='text-white' onClick={() => signOut()}>
          Out{' '}
        </button>
      </main>
    </>
  )
}
