/* eslint-disable multiline-ternary */
import useGetAllGames from '@/components/getAllgames'
import { IconGrid, IconRow } from '@/components/icons/icons'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'

export default function Shop() {
  const { data } = useGetAllGames()
  const [view, setView] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section className='body-font mt-64 text-gray-400'>
          <div className='px-1 sm:px-6 lg:px-0'>
            {/* <!-- Breadcrumb --> */}
            <div className='my-2 flex items-center overflow-x-auto whitespace-nowrap'>
              <Link href='/' className='text-gray-600 dark:text-gray-200'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  className='h-5 w-5'
                  viewBox='0 0 20 20'
                  fill='currentColor'
                >
                  <path d='M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z' />
                </svg>
              </Link>

              <span className='mx-5 text-gray-500 rtl:-scale-x-100 dark:text-gray-300'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  className='h-5 w-5'
                  viewBox='0 0 20 20'
                  fill='currentColor'
                >
                  <path
                    fillRule='evenodd'
                    d='M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z'
                    clipRule='evenodd'
                  />
                </svg>
              </span>
              <a
                href='#'
                className='text-gray-600 hover:underline dark:text-gray-200'
              >
                Account
              </a>
              <span className='mx-5 text-gray-500 rtl:-scale-x-100 dark:text-gray-300'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  className='h-5 w-5'
                  viewBox='0 0 20 20'
                  fill='currentColor'
                >
                  <path
                    fillRule='evenodd'
                    d='M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z'
                    clipRule='evenodd'
                  />
                </svg>
              </span>
              <a
                href='#'
                className='text-gray-600 hover:underline dark:text-gray-200'
              >
                Profile
              </a>
            </div>
            <div className='my-4 flex items-baseline justify-between border-b border-gray-200 pt-2 dark:border-gray-800'>
              {/* <!-- cantidad de juegos --> */}
              <div className='py-2'>
                <p className='text-md font-semibold text-black dark:text-white'>
                  {data?.length} Games
                </p>
              </div>
              {/* <!-- botones view --> */}
              <div className='flex items-center'>
                <button
                  type='button'
                  onClick={() => setView(true)}
                  className=' text-gray-400 hover:text-gray-500'
                >
                  <IconGrid />
                </button>
                <button
                  type='button'
                  onClick={() => setView(false)}
                  className='ml-4 text-gray-400 hover:text-gray-500'
                >
                  <IconRow />
                </button>
                <button
                  type='button'
                  className='-m-2 ml-4 p-2 text-gray-400 hover:text-gray-500 sm:ml-6 lg:hidden'
                >
                  <span className='sr-only'>Filters</span>
                </button>
              </div>
            </div>

            <section aria-labelledby='products-heading' className='pt-2 pb-24'>
              <h2 id='products-heading' className='sr-only'>
                Products
              </h2>

              <div className='grid grid-cols-1 gap-x-2 gap-y-10 lg:grid-cols-6'>
                {/* Filters izquierdos */}
                <div className='hidden rounded-md bg-blackOne lg:block'>
                  <div className='mx-2 my-2 rounded-md bg-grisTwo'>
                    <h3 className='py-64' />
                  </div>
                </div>

                {/* grid */}
                <div className='lg:col-span-5'>
                  {/* otros filtros */}
                  <div className=' flex justify-between rounded-md bg-blackOne py-4 dark:bg-blackOne'>
                    <div className='px-2'>dasdasdasda</div>
                    <div className='px-4'>
                      <label
                        htmlFor='search'
                        className='sr-only mb-2 text-sm font-medium text-gray-900 dark:text-white'
                      >
                        Search
                      </label>
                      <div className='relative'>
                        <div className='pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3'>
                          <svg
                            aria-hidden='true'
                            className='h-5 w-5 text-gray-500 dark:text-gray-400'
                            fill='none'
                            stroke='currentColor'
                            viewBox='0 0 24 24'
                            xmlns='http://www.w3.org/2000/svg'
                          >
                            <path
                              stroke-linecap='round'
                              stroke-linejoin='round'
                              stroke-width='2'
                              d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z'
                            />
                          </svg>
                        </div>
                        <input
                          type='search'
                          id='search'
                          className='block w-full appearance-none rounded-lg bg-gray-50 p-4 pl-10 text-sm text-gray-900 focus:outline-none focus:ring-1 focus:ring-grisClaro  dark:border-gray-600 dark:bg-grisTwo dark:text-white dark:placeholder-gray-200'
                          placeholder='Search'
                        />
                      </div>
                    </div>
                  </div>
                  {/* Games grid */}

                  <div className='container mx-auto mt-2'>
                    <div className='flex flex-wrap'>
                      {data?.slice(0, 16).map((game) =>
                        view ? (
                          <div
                            key={game.id}
                            className='w-full p-1 md:w-1/3 lg:w-1/3'
                          >
                            <div
                              style={{
                                backgroundImage: `url(${game.background_image})`
                              }}
                              className='flex h-[300px] w-full items-end overflow-hidden rounded-lg bg-cover bg-center object-cover object-center shadow-xl'
                            >
                              <div className='w-full overflow-hidden rounded-b-lg bg-grisTwo/30 backdrop-blur-md '>
                                <h2 className='text-md p-2 font-semibold text-white '>
                                  {game.name}
                                </h2>
                                <p className='mt-2 text-lg uppercase tracking-wider text-blue-500'>
                                  Website
                                </p>
                              </div>
                            </div>
                          </div>
                        ) : (
                          <div
                            key={game.id}
                            className='my-2 w-full rounded-md bg-grisOne lg:w-full'
                          >
                            <div className='flex items-center justify-between'>
                              <div className='flex items-center rounded-md'>
                                <Image
                                  className='rounded-md'
                                  src={game.background_image}
                                  width={150}
                                  height={100}
                                  alt={game.slug}
                                  loading='lazy'
                                />
                                <h2 className='text-md px-8 font-semibold text-white '>
                                  {game.name}
                                </h2>
                              </div>
                              <div className='px-6'>
                                <h3 className='font-bold text-white'>
                                  $ {game.price}
                                </h3>
                              </div>
                            </div>
                          </div>
                        )
                      )}
                    </div>
                  </div>
                  {/* <!-- pagination --> */}
                  <div className='flex justify-center py-10'>
                    <a
                      href='#'
                      className='mx-1 flex cursor-not-allowed items-center justify-center rounded-md bg-white px-4 py-2 capitalize text-gray-500 rtl:-scale-x-100 dark:bg-gray-800 dark:text-gray-600'
                    >
                      <svg
                        xmlns='http://www.w3.org/2000/svg'
                        className='h-5 w-5'
                        viewBox='0 0 20 20'
                        fill='currentColor'
                      >
                        <path
                          fill-rule='evenodd'
                          d='M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z'
                          clip-rule='evenodd'
                        />
                      </svg>
                    </a>

                    <a
                      href='#'
                      className='mx-1 hidden transform rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blackOne hover:text-white dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blackOne dark:hover:text-gray-200 sm:inline'
                    >
                      1
                    </a>

                    <a
                      href='#'
                      className='mx-1 hidden transform rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blue-500 hover:text-white dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blue-500 dark:hover:text-gray-200 sm:inline'
                    >
                      2
                    </a>

                    <a
                      href='#'
                      className='mx-1 hidden transform rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blue-500 hover:text-white dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blue-500 dark:hover:text-gray-200 sm:inline'
                    >
                      ...
                    </a>

                    <a
                      href='#'
                      className='mx-1 hidden transform rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blue-500 hover:text-white dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blue-500 dark:hover:text-gray-200 sm:inline'
                    >
                      9
                    </a>

                    <a
                      href='#'
                      className='mx-1 hidden transform rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blue-500 hover:text-white dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blue-500 dark:hover:text-gray-200 sm:inline'
                    >
                      10
                    </a>

                    <a
                      href='#'
                      className='mx-1 flex transform items-center justify-center rounded-md bg-white px-4 py-2 text-gray-700 transition-colors duration-300 hover:bg-blue-500 hover:text-white rtl:-scale-x-100 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-blue-500 dark:hover:text-gray-200'
                    >
                      <svg
                        xmlns='http://www.w3.org/2000/svg'
                        className='h-5 w-5'
                        viewBox='0 0 20 20'
                        fill='currentColor'
                      >
                        <path
                          fill-rule='evenodd'
                          d='M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z'
                          clip-rule='evenodd'
                        />
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  )
}
